M48
; DRILL file {KiCad 9.0.4} date 2026-03-29T23:41:34+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-29T23:41:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
%
G90
G05
T1
X214.926Y-44.163
X245.0Y-55.8
X245.0Y-168.0
T2
X256.435Y-149.022
X256.435Y-154.802
M30
